// Work state (§4.3, §4.4, §5): scan work/, derive per-shrine status, and implement `start` / `clear`.
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  TEMPLATES, defaultTemplate, fillTemplate, localDate, setFrontmatter, validateClear,
  type ClearCheck, type TemplateName, type WorkFile,
} from './clear.ts';
import type { Config } from './config.ts';
import type { GitWorkInfo } from './git.ts';
import type { ShrineStatus } from './mapdata.ts';
import type { Diagnostic, Shrine, World } from './types.ts';
import { parseWriteup } from './writeup.ts';

export const WORK_DIR = 'work';
export const TEMPLATES_DIR = 'templates';

/** Everything read from one `work/<id>/` folder. */
export interface WorkFolder {
  writeup: string | null;
  files: WorkFile[];
  /** NEXT.md contents and mtime (ms since epoch). */
  next: { text: string; mtime: number } | null;
}

export interface ShrineWork {
  status: ShrineStatus;
  startedAt?: string;
  clearedAt?: string;
  /** Whether the cleared WRITEUP.md matches HEAD. Uncommitted clears render dashed (§4.4). */
  committed: boolean;
  /** Commit timestamps (unix seconds) touching `work/<id>/`. */
  touches: number[];
  /** In-progress shrines only. `since` (ms) drives the 14-day fade: NEXT.md mtime, else last touch, else started. */
  campfire?: { note: string | null; since: number | null };
  hours?: number;
  remnote: number;
  /** Markdown body of a cleared write-up (rendered in the detail panel). */
  writeup?: string;
  /** Failing clear checks when WRITEUP.md says cleared but the clear isn't valid (the shrine stays in progress). */
  clearProblems?: string[];
}

/** Values for `{{placeholders}}` in template files that depend only on the shrine (so scaffolds can be recognised later). */
export function templateValues(shrine: Shrine): Record<string, string> {
  return { id: shrine.id, title: shrine.title, module: shrine.id.replace(/-/g, '_') };
}

/** Build output and caches: generated by running the scaffold, so never artefacts (and possibly large). */
const SKIP_DIRS = new Set(['node_modules', '__pycache__', 'build']);

/** Recursive file list relative to `dir`. Skips dot-directories and SKIP_DIRS. */
function listFiles(dir: string, prefix = ''): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    const rel = prefix ? `${prefix}/${name}` : name;
    const st = statSync(full);
    if (st.isDirectory()) {
      if (name.startsWith('.') || SKIP_DIRS.has(name)) continue;
      out.push(...listFiles(full, rel));
    } else if (st.isFile()) out.push(rel);
  }
  return out;
}

/** Template directories as `path → [template, ...]`, so work files can be compared with their scaffold. */
function templateIndex(root: string): Map<string, TemplateName[]> {
  const index = new Map<string, TemplateName[]>();
  for (const t of TEMPLATES) {
    const dir = join(root, TEMPLATES_DIR, t);
    if (!existsSync(dir)) continue;
    for (const f of listFiles(dir)) index.set(f, [...(index.get(f) ?? []), t]);
  }
  return index;
}

function isTemplateCopy(root: string, index: Map<string, TemplateName[]>, shrine: Shrine, rel: string, content: Buffer): boolean {
  for (const t of index.get(rel) ?? []) {
    const tpl = readFileSync(join(root, TEMPLATES_DIR, t, rel));
    if (tpl.equals(content)) return true;
    if (fillTemplate(tpl.toString('utf8'), templateValues(shrine)) === content.toString('utf8')) return true;
  }
  return false;
}

/** Read one work folder. */
export function readWorkFolder(root: string, shrine: Shrine, index = templateIndex(root)): WorkFolder {
  const dir = join(root, WORK_DIR, shrine.id);
  const wfile = join(dir, 'WRITEUP.md');
  const nfile = join(dir, 'NEXT.md');
  const files = listFiles(dir).map((path) => {
    const size = statSync(join(dir, path)).size;
    // Only small files can be template copies; don't read large results or binaries.
    const templateCopy = size < 256 * 1024 && index.has(path) && isTemplateCopy(root, index, shrine, path, readFileSync(join(dir, path)));
    return { path, templateCopy };
  });
  return {
    writeup: existsSync(wfile) ? readFileSync(wfile, 'utf8') : null,
    files,
    next: existsSync(nfile) ? { text: readFileSync(nfile, 'utf8'), mtime: statSync(nfile).mtimeMs } : null,
  };
}

/** Every `work/<id>/` folder whose id is a shrine. Unknown folders are left to `lintWorkFolders`. */
export function scanWork(root: string, world: World): Map<string, WorkFolder> {
  const out = new Map<string, WorkFolder>();
  const dir = join(root, WORK_DIR);
  if (!existsSync(dir)) return out;
  const index = templateIndex(root);
  for (const id of readdirSync(dir).sort()) {
    const shrine = world.shrineById.get(id);
    if (!shrine || !statSync(join(dir, id)).isDirectory()) continue;
    out.set(id, readWorkFolder(root, shrine, index));
  }
  return out;
}

/** Number of proposals per proposing shrine (`from:` in proposed.yaml). */
export function proposalCounts(world: World): Map<string, number> {
  const out = new Map<string, number>();
  for (const s of world.shrines) if (s.from) out.set(s.from, (out.get(s.from) ?? 0) + 1);
  return out;
}

/** First non-blank line of NEXT.md, without Markdown heading or list markers. */
export function campfireNote(text: string): string | null {
  const line = text.split(/\r?\n/).map((l) => l.trim()).find(Boolean);
  if (!line) return null;
  return line.replace(/^(#+|[-*+]|\d+\.)\s+/, '').trim() || null;
}

const EMPTY_GIT: GitWorkInfo = { touches: new Map(), dirty: null };

/**
 * Derived work state (§4.4), a pure function of the scanned folders, git info and config.
 * A shrine counts as cleared only if its WRITEUP.md says so *and* the clear still validates (§0.2),
 * so hand-editing `status: cleared` doesn't clear anything. Temples are resolved to a fixed point
 * because their validity depends on other clears.
 */
export function deriveWorkState(world: World, folders: Map<string, WorkFolder>, config: Config, git: GitWorkInfo = EMPTY_GIT): Map<string, ShrineWork> {
  const proposals = proposalCounts(world);
  const claimed = [...folders].filter(([, f]) => f.writeup !== null && parseWriteup(f.writeup).frontmatter?.status === 'cleared');
  const cleared = new Set<string>();
  const failures = new Map<string, ClearCheck[]>();
  for (let changed = true; changed; ) {
    changed = false;
    for (const [id, f] of claimed) {
      if (cleared.has(id)) continue;
      const res = validateClear({
        shrine: world.shrineById.get(id)!, writeup: f.writeup, files: f.files, minWords: config.writeup.minWords,
        isCleared: (n) => cleared.has(n), proposals: proposals.get(id) ?? 0,
      });
      if (res.ok) {
        cleared.add(id);
        failures.delete(id);
        changed = true;
      } else failures.set(id, res.checks.filter((c) => !c.ok));
    }
  }

  const out = new Map<string, ShrineWork>();
  for (const s of world.shrines) {
    const touches = git.touches.get(s.id) ?? [];
    const folder = folders.get(s.id);
    if (!folder) {
      out.set(s.id, { status: 'untouched', committed: false, touches, remnote: 0 });
      continue;
    }
    const parsed = folder.writeup === null ? null : parseWriteup(folder.writeup, s.id);
    const fm = parsed?.frontmatter ?? null;
    const isCleared = cleared.has(s.id);
    const w: ShrineWork = {
      status: isCleared ? 'cleared' : 'in-progress',
      committed: isCleared && git.dirty !== null && !git.dirty.has(`${WORK_DIR}/${s.id}/WRITEUP.md`),
      touches,
      remnote: fm?.remnote.length ?? 0,
    };
    if (fm?.started) w.startedAt = fm.started;
    if (isCleared && fm?.cleared) w.clearedAt = fm.cleared;
    if (fm?.hours !== undefined) w.hours = fm.hours;
    if (isCleared && parsed) w.writeup = parsed.body;
    if (!isCleared) {
      const lastTouch = touches.length ? touches[touches.length - 1]! * 1000 : null;
      const started = w.startedAt ? new Date(`${w.startedAt}T12:00:00`).getTime() : null;
      w.campfire = {
        note: folder.next ? campfireNote(folder.next.text) : null,
        since: folder.next?.mtime ?? lastTouch ?? started,
      };
    }
    const fails = failures.get(s.id);
    if (fails) w.clearProblems = fails.map((c) => (c.detail ? `${c.label} (${c.detail})` : c.label));
    out.set(s.id, w);
  }
  return out;
}

/** Scan and derive in one go. */
export function readWorkState(root: string, world: World, config: Config, git?: GitWorkInfo): Map<string, ShrineWork> {
  return deriveWorkState(world, scanWork(root, world), config, git);
}

/** Warn about write-ups that claim `status: cleared` but don't pass the clear checks. */
export function lintClears(work: Map<string, ShrineWork>): Diagnostic[] {
  const out: Diagnostic[] = [];
  for (const [id, w] of work) {
    if (!w.clearProblems) continue;
    out.push({
      severity: 'warning', code: 'invalid-clear', file: `${WORK_DIR}/${id}/WRITEUP.md`, line: 1,
      message: `says cleared but the clear doesn't validate, so the map shows it in progress: ${w.clearProblems.join('; ')}`,
    });
  }
  return out;
}

// ---------------------------------------------------------------------------------------------
// stratum start

export interface StartOptions {
  force?: boolean;
  template?: TemplateName;
  today?: string;
}

export type StartResult =
  | { outcome: 'started'; template: TemplateName; created: string[] }
  | { outcome: 'already'; status: ShrineStatus; note: string | null }
  | { outcome: 'refused'; reason: string };

/** Copy a template directory, filling placeholders in text files. Never overwrites. */
function copyTemplateDir(src: string, dest: string, values: Record<string, string>, created: string[], prefix: string) {
  for (const rel of listFilesWithDotfiles(src)) {
    const to = join(dest, rel);
    if (existsSync(to)) continue;
    mkdirSync(dirname(to), { recursive: true });
    const buf = readFileSync(join(src, rel));
    if (buf.includes(0)) copyFileSync(join(src, rel), to);
    else writeFileSync(to, fillTemplate(buf.toString('utf8'), values));
    created.push(`${prefix}/${rel}`);
  }
}

/** Like listFiles, but templates may ship dotfiles such as .gitignore. */
function listFilesWithDotfiles(dir: string, prefix = ''): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    const rel = prefix ? `${prefix}/${name}` : name;
    if (statSync(full).isDirectory()) out.push(...listFilesWithDotfiles(full, rel));
    else out.push(rel);
  }
  return out;
}

/**
 * `stratum start <id>` (§11): scaffold `work/<id>/` and mark it in progress.
 * Refuses a locked temple without `--force`. TODO(M3): also refuse hidden shrines without `--force`;
 * until visibility lands every shrine counts as revealed.
 */
export function startShrine(root: string, world: World, work: Map<string, ShrineWork>, id: string, opts: StartOptions = {}): StartResult {
  const shrine = world.shrineById.get(id);
  if (!shrine) return { outcome: 'refused', reason: `unknown shrine "${id}"` };
  const dir = join(root, WORK_DIR, id);
  const wfile = join(dir, 'WRITEUP.md');
  const current = work.get(id);
  if (existsSync(wfile)) {
    return { outcome: 'already', status: current?.status ?? 'in-progress', note: current?.campfire?.note ?? null };
  }
  if (shrine.kind === 'temple' && !opts.force) {
    const missing = shrine.needs.filter((n) => work.get(n)?.status !== 'cleared');
    if (missing.length) return { outcome: 'refused', reason: `temple is locked; not yet cleared: ${missing.join(', ')} (use --force to start anyway)` };
  }

  const template = opts.template ?? defaultTemplate(shrine);
  const tdir = join(root, TEMPLATES_DIR);
  const values = { ...templateValues(shrine), started: opts.today ?? localDate(), done: shrine.done.trim(), prompt: shrine.prompt.trim() };
  const created: string[] = [];
  const prefix = `${WORK_DIR}/${id}`;
  const fresh = !existsSync(dir) || readdirSync(dir).length === 0;
  mkdirSync(dir, { recursive: true });
  // Only scaffold code into a new folder; an existing folder already holds the user's own files.
  // Code templates only get shrine-derived values, so untouched scaffolds can be recognised (they aren't artefacts).
  if (fresh && existsSync(join(tdir, template))) copyTemplateDir(join(tdir, template), dir, templateValues(shrine), created, prefix);
  for (const name of ['WRITEUP.md', 'NEXT.md']) {
    const to = join(dir, name);
    if (existsSync(to)) continue;
    const src = join(tdir, name);
    let text = existsSync(src) ? fillTemplate(readFileSync(src, 'utf8'), values) : name === 'WRITEUP.md' ? `---\nshrine: ${id}\n---\n` : 'Just set out.\n';
    if (name === 'WRITEUP.md') text = setFrontmatter(text, { shrine: id, status: 'in-progress', started: values.started });
    writeFileSync(to, text);
    created.push(`${prefix}/${name}`);
  }
  return { outcome: 'started', template, created };
}

// ---------------------------------------------------------------------------------------------
// stratum clear

export type ClearOutcome =
  | { outcome: 'cleared'; date: string; checks: ClearCheck[]; shrine: Shrine; commit: string }
  | { outcome: 'already'; date: string | null; shrine: Shrine }
  | { outcome: 'failed'; checks: ClearCheck[]; shrine: Shrine }
  | { outcome: 'unknown'; reason: string };

/** Shell-quote a commit message for the suggested command. */
const quote = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;

/**
 * `stratum clear <id>` (§5): validate, and on success stamp `status: cleared` and `cleared: <today>`.
 * Never commits; returns a suggested command instead.
 */
export function clearShrine(root: string, world: World, config: Config, id: string, opts: { today?: string } = {}): ClearOutcome {
  const shrine = world.shrineById.get(id);
  if (!shrine) return { outcome: 'unknown', reason: `unknown shrine "${id}"` };
  const folders = scanWork(root, world);
  const work = deriveWorkState(world, folders, config);
  if (work.get(id)?.status === 'cleared') return { outcome: 'already', date: work.get(id)!.clearedAt ?? null, shrine };

  const folder = folders.get(id) ?? { writeup: null, files: [], next: null };
  const res = validateClear({
    shrine, writeup: folder.writeup, files: folder.files, minWords: config.writeup.minWords,
    isCleared: (n) => work.get(n)?.status === 'cleared', proposals: proposalCounts(world).get(id) ?? 0,
  });
  if (!res.ok) return { outcome: 'failed', checks: res.checks, shrine };

  const date = opts.today ?? localDate();
  const wfile = join(root, WORK_DIR, id, 'WRITEUP.md');
  writeFileSync(wfile, setFrontmatter(folder.writeup!, { status: 'cleared', cleared: date }));
  const paths = [`${WORK_DIR}/${id}`, ...(shrine.kind === 'tower' ? ['world/proposed.yaml'] : [])];
  const commit = `git add ${paths.join(' ')} && git commit -m ${quote(`Clear ${id}: ${shrine.title}`)}`;
  return { outcome: 'cleared', date, checks: res.checks, shrine, commit };
}
